language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database dreamjob;' -U postgres

sudo: false

env:
  global:
    - CODECOV_TOKEN="4f2a419e-c5e6-44de-b455-44f1f7e2de09"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -s_manannikov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always